"""
Nifty 500 Stock List
====================
Complete list of Nifty 500 constituents with .NS suffix for yfinance.
"""

# Nifty 500 stock symbols (as of Dec 2024)
# Source: NSE India
NIFTY_500_SYMBOLS = [
    "3MINDIA", "ABB", "ACC", "AIAENG", "APLAPOLLO", "AUBANK", "AARTIIND", 
    "AAVAS", "ABBOTINDIA", "ABCAPITAL", "ABFRL", "AEGISLOG", "AFFLE", 
    "AJANTPHARM", "ALKEM", "ALLCARGO", "ALOKINDS", "AMARAJABAT", "AMBUJACEM",
    "ANGELONE", "APCOTEXIND", "APARINDS", "APOLLOHOSP", "APOLLOTYRE", "APTUS",
    "ARE&M", "ARVIND", "ASHOKLEY", "ASIANPAINT", "ASTERDM", "ASTRAL",
    "ATUL", "AUROPHARMA", "AVANTIFEED", "AXISBANK", "BASF", "BEML",
    "BEL", "BHARATFORG", "BHEL", "BPCL", "BHARTIARTL", "BIOCON",
    "BIRLACORPN", "BLUESTARCO", "BOSCHLTD", "BRIGADE", "BRITANNIA", "BSOFT",
    "CESC", "CGCL", "CGPOWER", "CIEINDIA", "CIPLA", "COALINDIA",
    "COCHINSHIP", "COFORGE", "COLPAL", "CONCORDBIO", "COROMANDEL", "CROMPTON",
    "CUB", "CUMMINSIND", "CYIENT", "DABUR", "DALBHARAT", "DCMSHRIRAM",
    "DEEPAKFERT", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "DIVISLAB", "DIXON",
    "DLF", "DMART", "DRREDDY", "EIDPARRY", "EIHOTEL", "ELECON",
    "ELGIEQUIP", "EMAMILTD", "ENDURANCE", "ENGINERSIN", "EPIGRAL", "EQUITASBNK",
    "ERIS", "ESCORT", "EXIDEIND", "FEDERALBNK", "FINEORG", "FIRSTSOUR",
    "FLUOROCHEM", "FMGOETZE", "FSL", "GAIL", "GALAXYSURF", "GARFIBRES",
    "GICRE", "GILLETTE", "GLAXO", "GLENMARK", "GMRINFRA", "GNFC",
    "GODFRYPHLP", "GODREJAGRO", "GODREJCP", "GODREJIND", "GODREJPROP", "GPPL",
    "GRANULES", "GRAPHITE", "GRASIM", "GSFC", "GSPL", "GUJGASLTD",
    "GUJALKALI", "HAL", "HATSUN", "HAVELLS", "HCLTECH", "HDFCAMC",
    "HDFCBANK", "HDFCLIFE", "HEIDELBERG", "HEROMOTOCO", "HFCL", "HINDALCO",
    "HINDCOPPER", "HINDPETRO", "HINDUNILVR", "HINDZINC", "HOMEFIRST", "HONAUT",
    "HSCL", "HUDCO", "IBREALEST", "ICICIBANK", "ICICIGI", "ICICIPRULI",
    "IDBI", "IDEA", "IDFCFIRSTB", "IEX", "IIFL", "IILF",
    "INDHOTEL", "INDIACEM", "INDIAMART", "INDIANB", "INDIGO", "INDUSINDBK",
    "INDUSTOWER", "INFIBEAM", "INFY", "INGERRAND", "INTELLECT", "IOC",
    "IPCALAB", "IRB", "IRCON", "IRCTC", "IRFC", "ITC",
    "ITDC", "JBCHEPHARM", "JKCEMENT", "JKPAPER", "JKTYRE", "JMFINANCIL",
    "JSL", "JSWENERGY", "JSWINFRA", "JSWSTEEL", "JTEKTINDIA", "JUBLFOOD",
    "JUBLINGREA", "JUBLPHARMA", "JUSTDIAL", "JYOTHYLAB", "KAJARIACER", "KALPATPOWR",
    "KANSAINER", "KARURVYSYA", "KAYNES", "KEC", "KFINTECH", "KIOCL",
    "KIRLOSENG", "KITEX", "KNRCON", "KPITTECH", "KRBL", "KSB",
    "LATENTVIEW", "LAURUSLABS", "LAXMIMACH", "LEMONTREE", "LICH OUSING", "LICI",
    "LINDEINDIA", "LT", "LTF", "LTIM", "LTTS", "LUPIN",
    "M&M", "M&MFIN", "MAHABANK", "MAHINDCIE", "MAHLIFE", "MAHLOG",
    "MAHSEAMLES", "MANAPPURAM", "MARICO", "MARUTI", "MASTEK", "MAXHEALTH",
    "MAZDOCK", "MCX", "MEDANTA", "METROPOLIS", "MFSL", "MGL",
    "MIDHANI", "MINDACORP", "MISHRA DHATU", "MMTC", "MOIL", "MOTHERSON",
    "MPHASIS", "MRF", "MRPL", "MSTCLTD", "MTAR", "MTARTECH",
    "MUKANDLTD", "MUTHOOTFIN", "NAM-INDIA", "NATIONALUM", "NAUKRI", "NAVINFLUOR",
    "NCC", "NESTLEIND", "NETWORK18", "NHPC", "NIACL", "NIITLTD",
    "NLCINDIA", "NMDC", "NOCIL", "NTPC", "NUVOCO", "OBEROIRLTY",
    "OFSS", "OIL", "OLECTRA", "ONGC", "ORIENTCEM", "ORIENTELEC",
    "PAYTM", "PCBL", "PDSL", "PEL", "PERSISTENT", "PETRONET",
    "PFC", "PFIZER", "PGHH", "PHOENIXLTD", "PIDILITIND", "PIIND",
    "PNB", "PNBHOUSING", "POLYCAB", "POLYMED", "POONAWALLA", "POWERGRID",
    "PPLPHARMA", "PRESTIGE", "PRINCEPIPE", "PRSMJOHNSN", "PSPPROJECT", "PTC",
    "PVRINOX", "QUESS", "RADICO", "RAIN", "RAJESHEXPO", "RALLIS",
    "RAMCOCEM", "RVNL", "RATNAMANI", "RAYMOND", "RBA", "RCF",
    "RECLTD", "REDINGTON", "RELAXO", "RELIANCE", "RHIM", "RITES",
    "ROSSARI", "ROUTE", "SBICARD", "SBILIFE", "SBIN", "SCHAEFFLER",
    "SCHNEIDER", "SCI", "SFL", "SHARDACROP", "SHILPAMED", "SHOPERSTOP",
    "SHREECEM", "SHRIRAMFIN", "SIEMENS", "SIGNATURE", "SIS", "SJVN",
    "SKFINDIA", "SOBHA", "SOLARINDS", "SONACOMS", "SONATSOFTW", "SOUTHBANK",
    "SPANDANA", "SPARC", "SPICEJET", "SRF", "STLTECH", "STAR",
    "STARCEMENT", "STOVEKRAFT", "SUDARSCHEM", "SUMICHEM", "SUNDARMFIN", "SUNDRMFAST",
    "SUNPHARMA", "SUNPHAADV", "SUNTV", "SUPRAJIT", "SUPREMEIND", "SURYAROSNI",
    "SUVENPHAR", "SUZLON", "SWANENERGY", "SYMPHONY", "SYNGENE", "TATACOMM",
    "TATACONSUM", "TATAELXSI", "TATAMOTORS", "TATAPOWER", "TATASTEEL", "TATVA",
    "TCI", "TCNS", "TCIEXP", "TCS", "TECHM", "TEJASNET",
    "THERMAX", "TIMKEN", "TIRUMALCHM", "TITAN", "TORNTPHARM", "TORNTPOWER",
    "TRENT", "TRIDENT", "TRITURBINE", "TTKPRESTIG", "TV18BRDCST", "TVSMOTOR",
    "UBL", "UCOBANK", "UFO", "ULTRACEMCO", "UNIONBANK", "UPL",
    "UTIAMC", "VAIBHAVGBL", "VAKRANGEE", "VARROC", "VBL", "VEDL",
    "VENKEYS", "VERITAS", "VGUARD", "VIJAYA", "VINATIORGA", "VIPIND",
    "VMART", "VOLTAS", "VSTIND", "VTL", "WABAG", "WELCORP",
    "WELSPUNIND", "WELSPUNLIV", "WESTLIFE", "WHIRLPOOL", "WIPRO", "WOCKPHARMA",
    "YESBANK", "ZEEL", "ZENSARTECH", "ZFCVINDIA", "ZOMATO", "ZYDUSLIFE"
]

def get_nse_symbols() -> list:
    """Get Nifty 500 symbols with .NS suffix for yfinance."""
    return [f"{symbol}.NS" for symbol in NIFTY_500_SYMBOLS]


def get_symbol_count() -> int:
    """Get total number of Nifty 500 symbols."""
    return len(NIFTY_500_SYMBOLS)


# Sample subset for testing
NIFTY_50_SAMPLE = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR",
    "SBIN", "BHARTIARTL", "KOTAKBANK", "ITC", "LT", "AXISBANK",
    "ASIANPAINT", "MARUTI", "HCLTECH", "SUNPHARMA", "TITAN", "ULTRACEMCO",
    "BAJFINANCE", "WIPRO", "NESTLEIND", "TATAMOTORS", "M&M", "NTPC",
    "POWERGRID", "ONGC", "JSWSTEEL", "TATASTEEL", "ADANIENT", "ADANIPORTS",
    "COALINDIA", "GRASIM", "TECHM", "INDUSINDBK", "BRITANNIA", "BAJAJFINSV",
    "HINDALCO", "DRREDDY", "CIPLA", "DIVISLAB", "EICHERMOT", "HEROMOTOCO",
    "APOLLOHOSP", "TATACONSUM", "SBILIFE", "HDFCLIFE", "UPL", "BPCL"
]

def get_nifty50_sample() -> list:
    """Get Nifty 50 sample symbols with .NS suffix for testing."""
    return [f"{symbol}.NS" for symbol in NIFTY_50_SAMPLE]
